---
title       : Regression Tree Illustrator
subtitle    : A tool to visually compare the affectiveness of different regression tree algorithms
author      : Rich Robinson
job         : Coursera Developing Data Products Course
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
github:
  user: smidge84
  repo: datasciencecoursera
  
--- .class #id2

## Motivations & Aims

* To produce an interactive and visual learning tool to help with understanding of prediction models.
* The prediction model choosen was **classification trees** (`rpart`) because they are quick to compute and simple to implement at this early stage.

--- &twocol w1:40% w2:60% 

## Implementation

* __Shiny__ was choosen as the implementation language as it provides a rapid way to get a prototype app running, where the package automatically takes care of the asthetics and has a large library of pre-defined widgets, allowing myself more time to focus on functional code.
* The __iris__ data set from the `datasets()` package was choosen because it is small in size but very good for illustration of various algorithms as the data splits very well into groups but has a slight crossover section which can allow for errors in prediction.

#### Some R Code

```{r echo=TRUE, message=FALSE}
require(datasets)
data(iris)
names(iris); dim(iris)
```




--- .class #id4

## Creation

The app provides the user with a simple set of options on the left, which predictors to include in the model, and shows various results and outputs in tabs on the right.
These outputs include:
* Text summary statistics & confusion matrix
* Graphical display of the regression tree model used for prediction
* A 2 variable plot of the testing data, highlighting which records were predicted correctly and those which were not.
* A 2 variable plot of the whole data set. This is useful for visual data exploration and an aid for predictor selection.

--- .class #id5

## Future Developments & Improvements

* Expansion to allow selection of other prediction algorithms _(Random Forests, Clustering, linear regression & splines etc.)_ with relevant outputs.
* User provided data sets, or user selection from a pre-defined list *(iris, mtcars, diamonds, galton etc.)*.
* User choice of outcome to predict and the list of available predictors would change accordingly.
* Improved graphics; use of GoogleVis for interactive plots such as a plot of clusters with an option to highlight if predicted correctly or not.
* Implementation of a __Submit__ button in the options panel. This was not possible as it would prevent the conditional panels from displaying correctly when changing between tabs.

