<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Rich Robinson" />


<title>Motor Trend Magazine</title>



<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="C:\Users\smidge\Documents\R\win-library\3.1\rmarkdown\rmd\h\bootstrap-3.3.1\css\bootstrap.css" type="text/css" />

</head>

<body>



<div id="header">
<h1 class="title">Motor Trend Magazine</h1>
<h4 class="author"><em>Rich Robinson</em></h4>
<h4 class="date"><em>Saturday, June 13, 2015</em></h4>
</div>


<div id="executive-summary" class="section level3">
<h3>Executive Summary</h3>
<p>This analysis explores the relationship between the transmission type of cars and the affect this has on fuel efficiency, measured in Miles per gallon (MPG). In particular the analysis needs to address the following points:</p>
<ul>
<li>Is an automatic or manual transmission better for MPG?</li>
<li>Quantify the difference in MPG between manual and automatic transmissions</li>
</ul>
<p>To answer the above questions the analysis will first look into the basic statistical properties of the data using mean and standard deviation to gain a general idea of trends. Followering this a more detailed statitical analysis will include the fitting of linear models which can be used to predict future values within a level of confidence. Further, the analysis will look into multivariable linear regression to improve model fit. This will cover selection of regressors and quantifying the outcomes to reach a conclusion.</p>
</div>
<div id="exploring-the-data-set" class="section level3">
<h3>Exploring the Data Set</h3>
<p>We are looking at the <em>mtcars</em> dataset provided in <code>R</code>, so let’s load it and have a look.</p>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>We can see from the above table there is much information in each record, but for our analysis we are only interested in the <code>mpg</code> and <code>am</code> columns. The <code>am</code> data is a boolean value signifying if the transmission type is manual (1) or automatic (0). For ease of later analysis, we shall convert this in a factor variable.</p>
<pre><code>## Source: local data frame [2 x 3]
## 
##       trans     mean       sd
## 1 automatic 17.14737 3.833966
## 2    manual 24.39231 6.166504</code></pre>
<p>The plot in Appendix A shows the recorded MPG by transmission type. By observation it can be seen that for cars with automatic transmission the MPG is generally lower than that of manual cars. Also the range of MPG values for automatic cars is much smaller (more concentrated) than that of manual cars. The blue point for each transmission type represents the mean value of the data. The mean MPG for cars with automatic transmission is 17.147 MPG and the mean for manual cars is 24.392 MPG, which confirms the trend of higher MPG for manual cars. To quantify the spread of the data we can look at the standard deviation from the mean. The standard deviation of automatic cars is 3.834 MPG which is lower than that for manual cars of 6.167 MPG, which indicates a range of values closer to the mean.</p>
</div>
<div id="hypothesis-testing" class="section level3">
<h3>Hypothesis Testing</h3>
<p>A two-sided T-test can quantify if there is a significant difference in the mean values of each group (automatic and manual) and something we should investigate more. Our default and alternative hypotheses are:</p>
<p><span class="math display">\[ H_0: \mu(automatic) = \mu(manual) \]</span> <span class="math display">\[ H_a: \mu(automatic) - \mu(manual) \neg 0 \]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># splitting the data into two subsets by transmission</span>
autoMPG &lt;-<span class="st"> </span>dat %&gt;%<span class="st"> </span><span class="kw">filter</span>(trans ==<span class="st"> &quot;automatic&quot;</span>)
manMPG &lt;-<span class="st"> </span>dat %&gt;%<span class="st"> </span><span class="kw">filter</span> (trans ==<span class="st"> &quot;manual&quot;</span>)
t1 &lt;-<span class="st"> </span><span class="kw">t.test</span>(autoMPG$mpg, manMPG$mpg, <span class="dt">paired =</span> <span class="ot">FALSE</span>, <span class="dt">var.equal =</span> <span class="ot">FALSE</span>)
t1</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  autoMPG$mpg and manMPG$mpg
## t = -3.7671, df = 18.332, p-value = 0.001374
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.280194  -3.209684
## sample estimates:
## mean of x mean of y 
##  17.14737  24.39231</code></pre>
<p>The results of a two-sided, non-paired t-test with unequal variances shows a p-value of 0.0013736. which is smaller than our significance rate of <code>0.05</code> (5%) which means we would reject the null hypothesis. Also the 95% confidence interval does not include zero which again indicates that there is a significant difference in means between the two groups and we should reject the null hypothesis.</p>
</div>
<div id="fitting-a-linear-regression-model" class="section level3">
<h3>Fitting a Linear Regression Model</h3>
<p>Let’s see what a basic relationship might show between the outcomes of the groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit1 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg ~<span class="st"> </span>am, <span class="dt">data =</span> dat)
<span class="kw">summary</span>(fit1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ am, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.3923 -3.0923 -0.2974  3.2439  9.5077 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   17.147      1.125  15.247 1.13e-15 ***
## am             7.245      1.764   4.106 0.000285 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.902 on 30 degrees of freedom
## Multiple R-squared:  0.3598, Adjusted R-squared:  0.3385 
## F-statistic: 16.86 on 1 and 30 DF,  p-value: 0.000285</code></pre>
<p>The summary information from our regression model shows little more information about our data subset. The coefficients of the model <span class="math inline">\(Y_i = \beta_0 + \beta_1 \times X_1\)</span> are; <span class="math inline">\(\beta_0 =\)</span> <strong>17.147</strong> (intercept) which is the mean MPG of cars with automatic transmission and <span class="math inline">\(\beta_1 =\)</span> <strong>7.245</strong> (slope) that on average cars with manual transmission have a higher MPG by <strong>7.245</strong> mpg. The <span class="math inline">\(R^2\)</span> value shows us how much of the variation is explained by the regression model. Here, this basic model explains only <strong>35.98%</strong> of the variation in MPG values.</p>
</div>
<div id="multivariable-linear-regression" class="section level3">
<h3>Multivariable Linear Regression</h3>
<p>It is logical that more attributes will affect MPG than just transmission type. Now lets look for strong correlations between other attributes and MPG using the <code>corr()</code> function.</p>
<pre><code>##    attr       corr
## 1   mpg  1.0000000
## 2    wt -0.8676594
## 3   cyl -0.8521620
## 4  disp -0.8475514
## 5    hp -0.7761684
## 6  drat  0.6811719
## 7    vs  0.6640389
## 8    am  0.5998324
## 9  carb -0.5509251
## 10 gear  0.4802848
## 11 qsec  0.4186840</code></pre>
<p>The output above shows that many attributes have a stronger affect on MPG than transmission type (am), namely weight, cylinders, displacement, horse power. This would suggest that a multivariate regression model would better predict the possible MPG of a vehicle, with predictors of weight, cylinders, displacement and horse power. Lets look into this further. (See appendix B for the code for the above calculation and a pairs plot for illustration)</p>
<p>However although some of the variables in our dataset correlate well with MPG, they might also correlate well with eachother. We ideally would like a regression model that is parsimonious, which means it has as few confounders as possible which are all orthogonal to one another. To help with this we can use <em>“Variance Inflation”</em> to show how a regressor (variable) will affect a model compared to when it is (ideally) orthogonal to other regressors. In <code>R</code> we use the <code>vif()</code> function in the <code>car</code> package.</p>
<pre><code>##    Regressor       vif
## 1       disp 21.620241
## 2        cyl 15.373833
## 3         wt 15.164887
## 4         hp  9.832037
## 5       carb  7.908747
## 6       qsec  7.527958
## 7       gear  5.357452
## 8         vs  4.965873
## 9         am  4.648487
## 10      drat  3.374620</code></pre>
<p>The above results show that the most influential regressor are displacement, cylinders, weight and horse power. Thus, lets try a linear model with these regressors plus our cofounder of interest, transmission. We can then use the <code>anova()</code> function to compare our two regression models.</p>
<pre><code>## Analysis of Variance Table
## 
## Model 1: mpg ~ am
## Model 2: mpg ~ am + disp + cyl + wt + hp
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1     30 720.90                                  
## 2     26 163.12  4    557.78 22.226 4.507e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The results show a very small p-value which indicates the additional regressors in the second model are of significance in producing a btter regression model than out original. Recall that the original regresion model explained 35.98% of the variation. The new model explains <strong>85.51%</strong>. In comparison, a regression model using the remaining cofounders to model MPG has an <span class="math inline">\(R^2\)</span> value of 78.83%, so the new model better explains the variation in MPG than the cofounders we chose to omit.</p>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>In conclusion we can now say that even given the additional cofounders of displacement, cylinders, weight and horse power that car with manual transmission have better MPG than those with automatic transmission. From the summary information in Appendix C we can see that manual cars on average are <strong>1.56</strong>mpg higher. However the associated p-value is relatively high, so maybe a more sophistocated model is required for a high significance level. The residual plots in Appendix D show that the residuals are fairly evenly distributed around zero meaning that the model is more <em>homoskedastic</em> than <em>heteroskedastic</em> (non constant variance), which indicates the model is a <em>‘good’</em> fit. The plots also highlight a few high influence points (Chrysler Imperial &amp; Toyota Corolla). Further analysis could look specifically at these records and using <em>influence measures</em> assess the affect these have had on the model and would a more accurate model be possible if we chose to omit them.</p>
</div>
<div id="appendix-a---code-plot-mpg-vs-transmission" class="section level3">
<h3>Appendix A - Code: Plot: MPG vs Transmission</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span>mtcars %&gt;%<span class="st"> </span><span class="kw">select</span>(mpg, am)

## adding a new column with am variable as a factor
dat &lt;-<span class="st"> </span>dat %&gt;%<span class="st"> </span><span class="kw">mutate</span>(<span class="dt">trans =</span> <span class="kw">factor</span>(am, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;automatic&quot;</span>, <span class="st">&quot;manual&quot;</span>)))

g1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dat, <span class="kw">aes</span>(<span class="dt">x =</span> trans, <span class="dt">y =</span> mpg)) +<span class="st"> </span><span class="kw">geom_point</span>(<span class="dt">color =</span> dat$am<span class="dv">+2</span>)
g1 &lt;-<span class="st"> </span>g1 +<span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;MPG against Transmission Type&quot;</span>) +<span class="st"> </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Transmission Type&quot;</span>) +<span class="st"> </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Miles per Gallon (MPG)&quot;</span>)

## calculating some basic stats
stats &lt;-<span class="st"> </span>dat %&gt;%<span class="st"> </span><span class="kw">select</span>(mpg, trans) %&gt;%<span class="st"> </span><span class="kw">group_by</span>(trans) %&gt;%<span class="st"> </span><span class="kw">summarise_each</span>(<span class="kw">funs</span>(mean, sd))
stats

## adding the stats as reference points on plot
g1 &lt;-<span class="st"> </span>g1 +<span class="st"> </span><span class="kw">geom_point</span>(<span class="dt">data =</span> stats, <span class="kw">aes</span>(<span class="dt">x =</span> trans, <span class="dt">y =</span> mean), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">size =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="figs/app_a-1.png" title="Figure 1" alt="Figure 1" style="display: block; margin: auto;" /></p>
</div>
<div id="appendix-b---code-plot-correlation-between-attributes" class="section level3">
<h3>Appendix B - Code: Plot: Correlation between Attributes</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## calculating correlations of the data
foo &lt;-<span class="st"> </span><span class="kw">cor</span>(mtcars, mtcars$mpg)
corrs &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">attr =</span> <span class="kw">rownames</span>(foo), <span class="dt">corr =</span> foo[,<span class="dv">1</span>])
## arranging into order of significance by ABS value to preserve relationship (positive or negative)
corrs &lt;-<span class="st"> </span><span class="kw">arrange</span>(corrs, <span class="kw">desc</span>(<span class="kw">abs</span>(corr)))
corrs</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## selecting column numbers
col_nums &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">order</span>(<span class="kw">desc</span>(<span class="kw">abs</span>(foo))))
## creating pairs plot
<span class="kw">ggpairs</span>(<span class="kw">select</span>(mtcars, col_nums[<span class="dv">1</span>:<span class="dv">5</span>]), <span class="dt">title =</span> <span class="st">&quot;Pairs plot of most Significant Attributes towards MPG&quot;</span>)</code></pre></div>
<p><img src="figs/pairs_corr-1.png" title="Figure 2" alt="Figure 2" style="display: block; margin: auto;" /></p>
</div>
<div id="appendix-c---code-vif-regressor-selection" class="section level3">
<h3>Appendix C - Code: VIF &amp; Regressor Selection</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg ~<span class="st"> </span>., <span class="dt">data =</span> mtcars)
bar &lt;-<span class="st"> </span><span class="kw">vif</span>(fit)
vifs_long &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Regressor =</span> <span class="kw">names</span>(bar), <span class="dt">vif =</span> bar)
vifs_long &lt;-<span class="st"> </span><span class="kw">arrange</span>(vifs_long, <span class="kw">desc</span>(vif)) <span class="co"># arranging</span>
vifs_wide &lt;-<span class="st"> </span><span class="kw">dcast</span>(vifs_long, .~<span class="st"> </span>Regressor, <span class="dt">value.var=</span><span class="st">&quot;vif&quot;</span>)[, <span class="dv">2</span>:(<span class="kw">dim</span>(vifs_long)[<span class="dv">1</span>]+<span class="dv">1</span>)] <span class="co"># for better presentation</span>
vifs_long</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(fit2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ am + disp + cyl + wt + hp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5952 -1.5864 -0.7157  1.2821  5.5725 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 38.20280    3.66910  10.412 9.08e-11 ***
## am           1.55649    1.44054   1.080  0.28984    
## disp         0.01226    0.01171   1.047  0.30472    
## cyl         -1.10638    0.67636  -1.636  0.11393    
## wt          -3.30262    1.13364  -2.913  0.00726 ** 
## hp          -0.02796    0.01392  -2.008  0.05510 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.505 on 26 degrees of freedom
## Multiple R-squared:  0.8551, Adjusted R-squared:  0.8273 
## F-statistic:  30.7 on 5 and 26 DF,  p-value: 4.029e-10</code></pre>
</div>
<div id="appendix-d---plot-residual-plots" class="section level3">
<h3>Appendix D - Plot: Residual Plots</h3>
<p><img src="figs/app_d-1.png" title="" alt="" style="display: block; margin: auto;" /></p>
</div>



<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
